name: quailifier-bot
version: 0.1.0.0
github: "Reykudo/quailifier-bot"
license: BSD3
author: "Reykudo"
maintainer: "xraf07@gmail.com"
copyright: "2021 Reykudo"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Reykudo/quailifier-bot#readme>

dependencies:
  - base
  - aeson
  - bytestring
  - containers
  - either
  - ekg
  - ekg-core
  - foreign-store

  - env-extra
  - mtl
  - fast-logger
  - generic-deriving
  - http-client
  - http-client-tls
  - katip
  - monad-control
  - monad-logger
  # - monad-metrics
  - persistent >= 2.12.1.1
  - persistent-postgresql >= 2.12.1.1
  - persistent-template >= 2.12.0.0
  - esqueleto >= 3.5.0.0
  - product-profunctors
  - resource-pool
  - safe
  - safe-exceptions
  - say
  # - telegram-raw-api
  # - telegram-types
  - clock
  - cache
  - hashable
  - http-conduit
  - text
  - time
  - transformers
  - unliftio
  # - unordered-containers
  - wai
  - wai-extra
  - async
  # - wai-middleware-metrics
  - warp
  # - once
  # - forkable-monad
  - tg-bot-api-client-autogenerated
  - exceptions

library:
  source-dirs: src

executables:
  quailifier-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quailifier-bot

tests:
  quailifier-bot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quailifier-bot
