name: quailifier-bot
version: 0.1.0.0
github: "Reykudo/quailifier-bot"
license: BSD3
author: "Reykudo"
maintainer: "xraf07@gmail.com"
copyright: "2021 Reykudo"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Reykudo/quailifier-bot#readme>

dependencies:
  - base
  - servant
  - servant-server
  # - servant-swagger
  # - swagger2
  - text
  - wai
  - aeson
  - warp
  - bytestring
  - mtl
  - transformers
  - telegram-raw-api
  - hashable
  - telegram-types
  - servant-client
  - containers
  - http-client
  - servant
  - http-client-tls
  - retry
  - generic-deriving
  - env-extra
  # - opaleye
  - product-profunctors
  - time
  - postgresql-simple
  - aeson
  - bytestring
  - containers
  - ekg
  - ekg-core
  - fast-logger
  - foreign-store
  - katip
  - microlens
  - monad-control
  - monad-logger
  - monad-metrics
  - mtl
  - persistent >= 2.12.1.1
  - persistent-postgresql >= 2.12.1.1
  - persistent-template >= 2.12.0.0
  - safe
  - servant
  - servant-server
  - text
  - transformers
  - unordered-containers
  - wai
  - wai-extra
  - wai-middleware-metrics
  - warp
  - resource-pool
  - safe-exceptions
  - say
  - unliftio
  - either

library:
  source-dirs: src

executables:
  quailifier-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quailifier-bot

tests:
  quailifier-bot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quailifier-bot
